name: Build develop tag with Maven

on:
  push:
    branches: develop
  pull_request:
    branches: develop
    types: closed

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode package
    - name: Testing with Maven
      run: mvn test
      
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v3
      with: 
        name: build-result
        path: ./target/GCM-Sistema-Bancario-0.0.1-SNAPSHOT.jar

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: 'build-'

    
      
